- name: Install the Nvidia package
  community.general.pacman:
    name: nvidia-open
    state: present

- name: Install the Nvidia Settings tool
  community.general.pacman:
    name: nvidia-settings
    state: present
