- name: Install Open VPN
  community.general.pacman:
    name: [openvpn, networkmanager-openvpn]
    state: present

- name: Install Hashcat
  community.general.pacman:
    name: [hashcat, hashcat-utils, cuda]
    state: present

- name: Get SecLists from GitHub
  ansible.builtin.git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: "/usr/share/seclists"
    force: yes

- name: Get Markdown report templates from GitHub
  ansible.builtin.git:
    repo: https://github.com/Wandmalfarbe/pandoc-latex-template.git
    dest: "/usr/share/pandoc"
    force: yes

- name: Bless Hex Editor
  community.general.pacman:
    name: [bless]
    state: present

- name: Netcat
  community.general.pacman:
    name: [gnu-netcat]
    state: present

- name: MITMProxy
  community.general.pacman:
    name: [mitmproxy]
    state: present
